In [15]:
import numpy as np
from IPython.display import Image, display

In [3]:
Image('./multilayer_nn_1.jpg')

NameError: name 'Image' is not defined


$$x_i$$

$$h_j = \sum_i w_{ij}x_i$$

$$h_j = f(\sum_i w_{ij}x_i)$$

$$y = f(\sum_j w_jh_j)$$

なお、活性化関数$f$は、シグモイド関数
$$f(x) = \displaystyle \frac{1}{1 + e^{-x}}$$
であり、閾値$\theta$は、$w_0x_0$と表すものとする

## ベクトル表現

### 入力層のノード数＝4
$$\vec{x} = \begin{pmatrix}
x_1 &
x_2 &
x_3 &
x_4
\end{pmatrix}$$
### 隠れ層のノード数＝5
$$\vec{h} = \begin{pmatrix}
h_1 &
h_2 &
h_3 &
h_4 &
h_5
\end{pmatrix}$$

### 出力層のノード数＝1

### 入力層と隠れ層との結合の重み
$$\vec{w} = \begin{pmatrix}
w_{11} & w_{12} & w_{13} & w_{14} & w_{15} \\
w_{21} & w_{22} & w_{23} & w_{24} & w_{25} \\
w_{31} & w_{32} & w_{33} & w_{34} & w_{35} \\
w_{41} & w_{42} & w_{43} & w_{44} & w_{45} 
\end{pmatrix}$$

### 隠れ層の出力

$$\vec{h} = \vec{w}\cdot\vec{x}$$

# 課題2
## 多層ニューラルネットワークNの出力を計算する

### ニューラルネットワークNについて
### 入力層のノード数＝4
### 隠れ層のノード数＝3
### 出力層のノード数＝2
### 隠れ層および出力層の活性化関数はシグモイド関数である
### 入力層では活性化関数を用いない

### 準備

In [17]:
# numpyをインポート
pass

In [18]:
# sigmoid関数を定義
pass

In [19]:
# 入力層、隠れ層、出力層のノード数を設定
pass

#乱数を発生させるシードを設定（毎回同じ数を発生させる）、シード(0～99)
pass

# 入力値xを4個発生させ、配列（ベクトル）Xに格納
X = np.random.randn(4)
X


array([-1.0668638 , -1.23057185,  0.06105078, -0.66244759])

### たとえば、np.random.randn(4) を使って、ランダムな入力値を4個発生させる。シード=45のとき、発生される入力値は、
<font color="Red">
array$([ 0.02637477,  0.2603217 , -0.39514554, -0.20430091])$
</font>
### となる。

In [20]:
# 入力層から隠れ層への重み配列を生成する。値は正規分布（平均＝0、分散＝0，1）に従うものとする。
pass


### たとえば、入力層から隠れ層への重み配列は、
<font color="Red">
array([[-0.12716327, -0.25968786,  0.02896809],　<br>
       [-0.08733046,  0.03940727,  0.09351055],  <br>
       [-0.00156847,  0.0259596 , -0.14733142],  <br>
       [ 0.08019266, -0.17507524, -0.04950519]])
</font>
### となる。


In [21]:
# 隠れ層から出力層への重み配列も同様に生成する。
pass

### たとえば、隠れ層から出力層への重み配列は、

<font color="Red">
array([[-0.10086008,  0.00252442],  <br>
       [-0.01215069, -0.15468732],  <br>
       [-0.0606944 , -0.13938127]])
</font>
### となる。


## 課題2解答欄
## 準備で生成した入力値と重み値とを使って、多層ニューラルネットワークNの出力$y_1$と$y_2$を計算しなさい。出力層のノード数が2個であるため、出力の個数も2個となる。

In [22]:
# 隠れ層への入力h_inを計算
#h_in =
pass

In [23]:
# 隠れ層からの出力h_outを計算
#h_out = 
pass

In [24]:
# 出力層への入力out_inを計算
#out_in = 
pass

In [25]:
# 出力層からの出力、すなわち、多層ニューラルネットワークの出力ｙを計算
#y = 
pass

### たとえば、ニューラルネットワークの出力は、
<font color="Red">
array([0.47818834, 0.46252782])
</font>
### となる。
